package dev.breezes.settlements.entities.villager.animations.definitions;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

public class BaseVillagerAnimation {

    public static final VillagerAnimationDefinition WALK_1 = new VillagerAnimationDefinition("walk_1", AnimationDefinition.Builder.withLength(2f)
            .looping()
            .addAnimation("villager",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-2f, 5f, -1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.25f, KeyframeAnimations.degreeVec(2f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(-2f, -2f, 1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75f, KeyframeAnimations.degreeVec(2f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(-2f, 4f, -1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.25f, KeyframeAnimations.degreeVec(2f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.5f, KeyframeAnimations.degreeVec(-2f, -3f, 1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.75f, KeyframeAnimations.degreeVec(2f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2f, KeyframeAnimations.degreeVec(-2f, 5f, -1f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("nose",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, -5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.5f, KeyframeAnimations.degreeVec(0f, 0f, -5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 5f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("arms",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.25f, KeyframeAnimations.posVec(0f, -0.35f, 0.35f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75f, KeyframeAnimations.posVec(0f, -0.35f, 0.35f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.25f, KeyframeAnimations.posVec(0f, -0.35f, 0.35f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.75f, KeyframeAnimations.posVec(0f, -0.35f, 0.35f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("arms",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-2.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.25f, KeyframeAnimations.degreeVec(1f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(-2.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75f, KeyframeAnimations.degreeVec(1f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(-2.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.25f, KeyframeAnimations.degreeVec(1f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.5f, KeyframeAnimations.degreeVec(-2.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.75f, KeyframeAnimations.degreeVec(1f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2f, KeyframeAnimations.degreeVec(-2.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_leg",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-20f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(-20f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.5f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2f, KeyframeAnimations.degreeVec(-20f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_leg",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(-20f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.5f, KeyframeAnimations.degreeVec(-20f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM))).build());

    public static final VillagerAnimationDefinition WALK_2 = new VillagerAnimationDefinition("walk_2", AnimationDefinition.Builder.withLength(2f).looping()
            .addAnimation("villager",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-2f, 5f, -1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.25f, KeyframeAnimations.degreeVec(2f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(-2f, -2f, 1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75f, KeyframeAnimations.degreeVec(2f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(-2f, 4f, -1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.25f, KeyframeAnimations.degreeVec(2f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.5f, KeyframeAnimations.degreeVec(-2f, -3f, 1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.75f, KeyframeAnimations.degreeVec(2f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2f, KeyframeAnimations.degreeVec(-2f, 5f, -1f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("nose",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 17f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, -17f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 17f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.5f, KeyframeAnimations.degreeVec(0f, 0f, -17f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 17f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("arms",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.25f, KeyframeAnimations.posVec(0f, -0.35f, 0.35f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75f, KeyframeAnimations.posVec(0f, -0.35f, 0.35f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.25f, KeyframeAnimations.posVec(0f, -0.35f, 0.35f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.75f, KeyframeAnimations.posVec(0f, -0.35f, 0.35f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("arms",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.25f, KeyframeAnimations.degreeVec(1.25f, 5.2f, 5.41f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75f, KeyframeAnimations.degreeVec(1.44f, -6.93f, -7.23f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.25f, KeyframeAnimations.degreeVec(1.25f, 5.2f, 5.41f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.5f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.75f, KeyframeAnimations.degreeVec(1.44f, -6.93f, -7.23f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_leg",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 3f, -3f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.125f, KeyframeAnimations.posVec(0f, -0.17f, -2.5f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1f, KeyframeAnimations.posVec(0f, 3f, -3f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.125f, KeyframeAnimations.posVec(0f, -0.17f, -2.5f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.5f, KeyframeAnimations.posVec(0f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2f, KeyframeAnimations.posVec(0f, 3f, -3f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("left_leg",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-20.6f, -18.34f, -6.53f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(-2.91f, -5.81f, -3.64f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(-20.6f, -18.34f, -6.53f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.0834333f, KeyframeAnimations.degreeVec(-2.91f, -5.81f, -3.64f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.5f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2f, KeyframeAnimations.degreeVec(-20.6f, -18.34f, -6.53f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_leg",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 3f, -3f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5834334f, KeyframeAnimations.posVec(0f, -0.17f, -2.5f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1f, KeyframeAnimations.posVec(0f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.5f, KeyframeAnimations.posVec(0f, 3f, -3f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.5834333f, KeyframeAnimations.posVec(0f, -0.17f, -2.5f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2f, KeyframeAnimations.posVec(0f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("right_leg",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(-20.6f, 18.34f, 6.53f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.625f, KeyframeAnimations.degreeVec(-2.91f, 5.81f, 3.64f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.5f, KeyframeAnimations.degreeVec(-20.6f, 18.34f, 6.53f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.625f, KeyframeAnimations.degreeVec(-2.91f, 5.81f, 3.64f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("head",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.125f, KeyframeAnimations.posVec(1f, -1f, -2f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.625f, KeyframeAnimations.posVec(-1f, -1f, -2f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.125f, KeyframeAnimations.posVec(1f, -1f, -2f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.625f, KeyframeAnimations.posVec(-1f, -1f, -2f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("head",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(-2.5f, 0.22f, -5f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5834334f, KeyframeAnimations.degreeVec(-2.5f, 0f, 5f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.0834333f, KeyframeAnimations.degreeVec(-2.5f, 0.22f, -5f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.5834333f, KeyframeAnimations.degreeVec(-2.5f, 0f, 5f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("torso",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.125f, KeyframeAnimations.posVec(0f, -1f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.625f, KeyframeAnimations.posVec(0f, -1f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.125f, KeyframeAnimations.posVec(0f, -1f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.625f, KeyframeAnimations.posVec(0f, -1f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("torso",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.125f, KeyframeAnimations.degreeVec(2.5f, -0.11f, 2.5f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.625f, KeyframeAnimations.degreeVec(2.5f, 0.11f, -2.5f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.125f, KeyframeAnimations.degreeVec(2.5f, -0.11f, 2.5f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.625f, KeyframeAnimations.degreeVec(2.5f, 0.11f, -2.5f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR))).build());

    public static final VillagerAnimationDefinition ARM_CROSS = new VillagerAnimationDefinition("arm_cross", AnimationDefinition.Builder.withLength(3f).looping()
            .addAnimation("arms",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(45f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.5f, KeyframeAnimations.degreeVec(45f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("left_hand",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, -90f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.5f, KeyframeAnimations.degreeVec(0f, 0f, -90f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("left_hand",
                    new AnimationChannel(AnimationChannel.Targets.SCALE,
                            new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.25f, KeyframeAnimations.scaleVec(0.6f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.75f, KeyframeAnimations.scaleVec(0.6f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("right_hand",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 90f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.5f, KeyframeAnimations.degreeVec(0f, 0f, 90f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("right_hand",
                    new AnimationChannel(AnimationChannel.Targets.SCALE,
                            new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.25f, KeyframeAnimations.scaleVec(0.6f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.75f, KeyframeAnimations.scaleVec(0.6f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR))).build());

    public static final VillagerAnimationDefinition NITWIT = new VillagerAnimationDefinition("nitwit",
            AnimationDefinition.Builder.withLength(5.48f)
                    .looping()
                    .addAnimation("head",
                            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                            AnimationChannel.Interpolations.LINEAR),
                                    new Keyframe(2.24f, KeyframeAnimations.degreeVec(-0.5f, 0f, 0f),
                                            AnimationChannel.Interpolations.LINEAR),
                                    new Keyframe(4.64f, KeyframeAnimations.degreeVec(22f, 0f, 0f),
                                            AnimationChannel.Interpolations.LINEAR),
                                    new Keyframe(5.48f, KeyframeAnimations.degreeVec(-30.21f, -16.24f, 1179.5f),
                                            AnimationChannel.Interpolations.LINEAR)))
                    .addAnimation("monobrow",
                            new AnimationChannel(AnimationChannel.Targets.POSITION,
                                    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                            AnimationChannel.Interpolations.LINEAR),
                                    new Keyframe(1.36f, KeyframeAnimations.posVec(0f, 0.75f, 0f),
                                            AnimationChannel.Interpolations.LINEAR),
                                    new Keyframe(2.48f, KeyframeAnimations.posVec(0f, 2f, 0f),
                                            AnimationChannel.Interpolations.LINEAR),
                                    new Keyframe(3.24f, KeyframeAnimations.posVec(0f, 1.75f, 0f),
                                            AnimationChannel.Interpolations.LINEAR)))
                    .addAnimation("monobrow",
                            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                    new Keyframe(1.36f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                            AnimationChannel.Interpolations.LINEAR),
                                    new Keyframe(2.28f, KeyframeAnimations.degreeVec(0f, 0f, 10f),
                                            AnimationChannel.Interpolations.LINEAR)))
                    .addAnimation("nose",
                            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                    new Keyframe(1.4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                            AnimationChannel.Interpolations.CATMULLROM),
                                    new Keyframe(2.56f, KeyframeAnimations.degreeVec(0f, 0f, 22.5f),
                                            AnimationChannel.Interpolations.CATMULLROM),
                                    new Keyframe(3.28f, KeyframeAnimations.degreeVec(0f, 0f, 235f),
                                            AnimationChannel.Interpolations.CATMULLROM),
                                    new Keyframe(3.52f, KeyframeAnimations.degreeVec(0f, 0f, 785f),
                                            AnimationChannel.Interpolations.CATMULLROM)))
                    .addAnimation("eyeball_right",
                            new AnimationChannel(AnimationChannel.Targets.POSITION,
                                    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                            AnimationChannel.Interpolations.LINEAR)))
                    .addAnimation("eyeball_right",
                            new AnimationChannel(AnimationChannel.Targets.SCALE,
                                    new Keyframe(2.08f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                            AnimationChannel.Interpolations.LINEAR),
                                    new Keyframe(4.8f, KeyframeAnimations.scaleVec(1.1f, 1.8f, 1f),
                                            AnimationChannel.Interpolations.LINEAR)))
                    .addAnimation("eyeball_left",
                            new AnimationChannel(AnimationChannel.Targets.POSITION,
                                    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                            AnimationChannel.Interpolations.LINEAR)))
                    .addAnimation("pupil_left",
                            new AnimationChannel(AnimationChannel.Targets.POSITION,
                                    new Keyframe(1.8f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                            AnimationChannel.Interpolations.LINEAR),
                                    new Keyframe(1.88f, KeyframeAnimations.posVec(0.01f, 0f, 0f),
                                            AnimationChannel.Interpolations.LINEAR),
                                    new Keyframe(2.96f, KeyframeAnimations.posVec(0.75f, 0f, 0f),
                                            AnimationChannel.Interpolations.LINEAR)))
                    .addAnimation("pupil_left",
                            new AnimationChannel(AnimationChannel.Targets.SCALE,
                                    new Keyframe(1.88f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                            AnimationChannel.Interpolations.LINEAR),
                                    new Keyframe(3.12f, KeyframeAnimations.scaleVec(1f, 0.5f, 1f),
                                            AnimationChannel.Interpolations.LINEAR)))
                    .addAnimation("pupil_right",
                            new AnimationChannel(AnimationChannel.Targets.POSITION,
                                    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                            AnimationChannel.Interpolations.LINEAR),
                                    new Keyframe(0.76f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                            AnimationChannel.Interpolations.LINEAR),
                                    new Keyframe(2.8f, KeyframeAnimations.posVec(-1f, 0f, 0f),
                                            AnimationChannel.Interpolations.LINEAR)))
                    .addAnimation("eyelid_right",
                            new AnimationChannel(AnimationChannel.Targets.POSITION,
                                    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                            AnimationChannel.Interpolations.LINEAR),
                                    new Keyframe(0.04f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                            AnimationChannel.Interpolations.LINEAR),
                                    new Keyframe(0.2f, KeyframeAnimations.posVec(0f, 0f, 1f),
                                            AnimationChannel.Interpolations.LINEAR)))
                    .addAnimation("eyelid_left",
                            new AnimationChannel(AnimationChannel.Targets.POSITION,
                                    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                            AnimationChannel.Interpolations.LINEAR),
                                    new Keyframe(0.04f, KeyframeAnimations.posVec(0f, 0f, 1f),
                                            AnimationChannel.Interpolations.LINEAR)))
                    .addAnimation("right_arm",
                            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                    new Keyframe(2.84f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                            AnimationChannel.Interpolations.CATMULLROM),
                                    new Keyframe(3f, KeyframeAnimations.degreeVec(0f, -25f, 27.5f),
                                            AnimationChannel.Interpolations.CATMULLROM),
                                    new Keyframe(3.08f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                            AnimationChannel.Interpolations.CATMULLROM),
                                    new Keyframe(3.2f, KeyframeAnimations.degreeVec(-23.89f, 15.8f, -53.9f),
                                            AnimationChannel.Interpolations.CATMULLROM),
                                    new Keyframe(3.32f, KeyframeAnimations.degreeVec(-45.61f, -15.38f, -91.06f),
                                            AnimationChannel.Interpolations.CATMULLROM),
                                    new Keyframe(3.6f, KeyframeAnimations.degreeVec(-157.48f, 5.54f, -177.56f),
                                            AnimationChannel.Interpolations.LINEAR),
                                    new Keyframe(3.76f, KeyframeAnimations.degreeVec(-99.51f, -1.89f, -107.2f),
                                            AnimationChannel.Interpolations.CATMULLROM),
                                    new Keyframe(4f, KeyframeAnimations.degreeVec(-73.72f, -14.03f, 15.27f),
                                            AnimationChannel.Interpolations.CATMULLROM)))
                    .addAnimation("right_hand",
                            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                    new Keyframe(2.44f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                            AnimationChannel.Interpolations.LINEAR),
                                    new Keyframe(2.92f, KeyframeAnimations.degreeVec(0f, 0f, 90f),
                                            AnimationChannel.Interpolations.LINEAR)))
                    .addAnimation("right_hand",
                            new AnimationChannel(AnimationChannel.Targets.SCALE,
                                    new Keyframe(2.44f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                            AnimationChannel.Interpolations.LINEAR),
                                    new Keyframe(2.68f, KeyframeAnimations.scaleVec(0.6f, 1f, 1f),
                                            AnimationChannel.Interpolations.LINEAR))).build());

    public static final VillagerAnimationDefinition SPIN = new VillagerAnimationDefinition("spin",
            AnimationDefinition.Builder.withLength(1f)
                    .looping()
                    .addAnimation("torso",
                            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                    new Keyframe(0.125f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                            AnimationChannel.Interpolations.LINEAR),
                                    new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(0f, -360f, 0f),
                                            AnimationChannel.Interpolations.LINEAR)))
                    .addAnimation("right_arm",
                            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                            AnimationChannel.Interpolations.LINEAR),
                                    new Keyframe(0.125f, KeyframeAnimations.degreeVec(0f, 45f, 90f),
                                            AnimationChannel.Interpolations.LINEAR),
                                    new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(0f, 45f, 90f),
                                            AnimationChannel.Interpolations.LINEAR),
                                    new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                            AnimationChannel.Interpolations.LINEAR)))
                    .addAnimation("right_hand",
                            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                            AnimationChannel.Interpolations.LINEAR),
                                    new Keyframe(0.125f, KeyframeAnimations.degreeVec(0f, 0f, 90f),
                                            AnimationChannel.Interpolations.LINEAR),
                                    new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(0f, 0f, 90f),
                                            AnimationChannel.Interpolations.LINEAR),
                                    new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                            AnimationChannel.Interpolations.LINEAR)))
                    .addAnimation("left_arm",
                            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                            AnimationChannel.Interpolations.LINEAR),
                                    new Keyframe(0.125f, KeyframeAnimations.degreeVec(0f, -45f, -90f),
                                            AnimationChannel.Interpolations.LINEAR),
                                    new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(0f, -45f, -90f),
                                            AnimationChannel.Interpolations.LINEAR),
                                    new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                            AnimationChannel.Interpolations.LINEAR)))
                    .addAnimation("left_hand",
                            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                            AnimationChannel.Interpolations.LINEAR),
                                    new Keyframe(0.125f, KeyframeAnimations.degreeVec(0f, 0f, -90f),
                                            AnimationChannel.Interpolations.LINEAR),
                                    new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(0f, 0f, -90f),
                                            AnimationChannel.Interpolations.LINEAR),
                                    new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                            AnimationChannel.Interpolations.LINEAR)))
                    .build());

}
